### ISSUE TITLE
Hard to manage dependencies/Libraries

### ISSUE THREAD

**Issue by esQmo** [razaghimahdi/Shopping-By-KMP#14]
You made your project so complex that it gives headache adding new libraries. You can"t even use anything "android.xxx", e.g: using Log.d(..) won't work, you can't use Parcelable or anything related to android framework.  What's wrong?

**Comment by razaghimahdi** [comment]
Hey man, what do u mean? of course u can't directly add android library to shared Module. add android library to android module. also about log, u have to use "println()" compose multiplatform directly doesn't support log

**Comment by razaghimahdi** [comment]
u can simply add ur library [here](https://github.com/razaghimahdi/Shopping-By-KMP/blob/master/shared/build.gradle.kts) 
```kotlin
  commonMain {
            dependencies {
                  // here
            }
        }
```

OR 
Since I added convention gradle plugin, u can manage ur gradle and add dependency [here](https://github.com/razaghimahdi/Shopping-By-KMP/blob/master/build-logic/convention/src/main/kotlin/SharedConventionPlugin.kt)

**Comment by razaghimahdi** [comment]
I suggest keep using convention gradle plugin
